import os
import time
import requests
from datetime import datetime

import streamlit as st
from streamlit_lottie import st_lottie

from agent.coordinator import AgentCoordinator
from agent.llm_provider import LLMFactory

st.set_page_config(page_title="Raven – Autonomous AI Developer", page_icon="🪶", layout="wide")


@st.cache_data
def load_lottieurl(url: str):
    try:
        r = requests.get(url)
        if r.status_code != 200:
            return None
        return r.json()
    except Exception:
        return None

# Clean Dark Mode SaaS CSS
st.markdown("""
<style>
    .stApp {
        background-color: #0d1117;
        color: #c9d1d9;
        font-family: 'Inter', -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif;
    }
    h1, h2, h3 {
        color: #58a6ff !important;
        font-family: 'Inter', sans-serif;
    }
    .stButton>button {
        background-color: #238636;
        color: white;
        border: 1px solid rgba(240, 246, 252, 0.1);
        border-radius: 6px;
        transition: all 0.2s ease;
        font-weight: 600;
    }
    .stButton>button:hover {
        background-color: #2ea043;
        border-color: rgba(240, 246, 252, 0.1);
    }
    .stTextInput>div>div>input {
        background-color: #161b22;
        color: #c9d1d9;
        border: 1px solid #30363d;
        border-radius: 6px;
    }
    div[data-testid="stExpander"] {
        background: #161b22;
        border: 1px solid #30363d;
        border-radius: 6px;
    }
    .console-terminal {
        background-color: #010409;
        border: 1px solid #30363d;
        color: #e6edf3;
        font-family: 'SFMono-Regular', Consolas, 'Liberation Mono', Menlo, monospace;
        padding: 16px;
        border-radius: 6px;
        height: 300px;
        overflow-y: auto;
        margin-bottom: 20px;
        font-size: 13px;
    }
    .terminal-line { margin: 4px 0; }
    .terminal-time { color: #8b949e; margin-right: 8px; }
</style>
""", unsafe_allow_html=True)

st.title("🪶 Raven: Autonomous AI Developer")
st.markdown("### Resolve GitHub Issues Instantly using Ensembles of AI Models")

with st.sidebar:
    st.header("System Status")
    providers = LLMFactory.create_all()
    st.markdown(f"🟢 **Available AI Models:** {len(providers)}")
    for name in providers.keys():
        st.caption(f"- `{name}`")
    st.markdown("🟢 **Docker Sandbox:** Ready")
    st.divider()
    st.info("Raven coordinates top LLMs to autonomously resolve GitHub issues. It writes code, tests it dynamically in a Docker container, and presents the best validated patch.")

tab_run, tab_dashboard, tab_bots = st.tabs(["Run Agent", "Dashboard", "Integrations"])

if "runs" not in st.session_state:
    st.session_state["runs"] = []

with tab_run:
    c1, c2 = st.columns([3, 1])
    with c1:
        issue_url = st.text_input("Enter GitHub Issue URL", "https://github.com/microsoft/vscode/issues/101")
        run_btn = st.button("🚀 Start Resolution", type="primary")
    with c2:
        lottie_ai = load_lottieurl("https://assets9.lottiefiles.com/packages/lf20_tno6cg2w.json")
        if lottie_ai:
            st_lottie(lottie_ai, height=100, key="run_header_anim")

    if run_btn:
        if not issue_url or not issue_url.startswith("https://github.com/"):
            st.error("❌ Please enter a valid GitHub issue URL (must start with https://github.com/)")
            st.stop()

        try:
            agent = AgentCoordinator()
        except RuntimeError as e:
            st.error(f"❌ Failed to initialize Raven agent: {str(e)}")
            st.stop()

        status_box = st.empty()
        result_box = st.container()
        
        st.markdown("### 📡 Live Execution Console")
        terminal_placeholder = st.empty()
        logs = []

        def render_terminal():
            log_divs = "".join([f"<div class='terminal-line'><span class='terminal-time'>[{time.strftime('%H:%M:%S')}]</span> {line}</div>" for line in logs])
            terminal_html = f"<div class='console-terminal'>{log_divs}</div>"
            terminal_placeholder.markdown(terminal_html, unsafe_allow_html=True)

        for msg_type, data in agent.solve_issue(issue_url):
            if msg_type == "event":
                logs.append(data)
                render_terminal()

            elif msg_type == "error":
                status_box.error(data)

            elif msg_type == "complete":
                status_box = st.empty()
                status_box.success(f"✅ Raven Workflow Complete! Patch generated by **{data.get('winner')}**")
                st.balloons()

                st.session_state["runs"].insert(
                    0,
                    {
                        "time": datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
                        "issue": issue_url,
                        "winner": data.get("winner"),
                    },
                )

                with result_box:
                    st.divider()
                    st.subheader("🎉 Verified Patch")
                    st.markdown(data.get("explanation", ""))
                    st.code(data.get("code", ""), language="python")
                    
                    with st.expander("Show Sandbox Verification Logs"):
                        st.code(data["verification_logs"], language="text")

with tab_dashboard:
    st.subheader("📊 Execution Dashboard")
    
    m1, m2, m3 = st.columns(3)
    m1.metric("Configured Models", str(len(LLMFactory.create_all())))
    m2.metric("Total Issues Resolved", str(len(st.session_state["runs"])))
    m3.metric("Docker Node", "Healthy")
    
    st.divider()
    st.subheader("🧾 Recent Resolutions")
    if st.session_state["runs"]:
        st.dataframe(st.session_state["runs"], use_container_width=True, hide_index=True)
    else:
        st.caption("No resolution runs yet.")

with tab_bots:
    st.subheader("🤖 Integrations")
    st.markdown("Run Raven from chat by sending a GitHub issue URL to your automated integrations.")
    st.markdown("Set one or both tokens in `.env`, then run the scripts from the repo root.")
    st.code(
        "\n".join(
            [
                "TELEGRAM_BOT_TOKEN=...",
                "DISCORD_BOT_TOKEN=...",
                "",
                "# Then run:",
                "python bots/telegram_bot.py",
                "python bots/discord_bot.py",
            ]
        ),
        language="bash",
    )
