package main

import (
	"encoding/json"
	"fmt"
	"log"
	"os"
	"os/signal"
	"syscall"

	"github.com/Shardz4/raven/broker"
	"github.com/Shardz4/raven/config"
	"github.com/Shardz4/raven/consensus"
	gh "github.com/Shardz4/raven/github"
	"github.com/Shardz4/raven/store"
	"github.com/nats-io/nats.go"
)

func main() {
	log.Println("🪶 Raven PR Agent Starting...")

	cfg := config.Load()
	db := store.NewClient(cfg.StoreServiceURL)
	prCreator := gh.NewPRCreator(cfg.GitHubToken)

	br, err := broker.New(cfg.NatsURL)
	if err != nil {
		log.Fatalf("❌ NATS connection failed: %v", err)
	}
	defer br.Close()

	// Helper to send progress log events
	emit := func(jobID, msg string) {
		event := broker.EventMsg{
			JobID:   jobID,
			Message: msg,
		}
		data, _ := json.Marshal(event)
		_ = br.Publish(broker.SubjectEventsPrefix+jobID, data)
		log.Printf("[job:%s] %s", jobID, msg)
	}

	_, err = br.QueueSubscribe(broker.SubjectConsensusWinner, "pr-group", func(msg *nats.Msg) {
		var winnerMsg broker.ConsensusWinnerMsg
		if err := json.Unmarshal(msg.Data, &winnerMsg); err != nil {
			log.Printf("❌ Failed to parse consensus winner message: %v", err)
			return
		}

		go func() {
			jobID := winnerMsg.JobID
			var report consensus.Report
			if err := json.Unmarshal(winnerMsg.Report, &report); err != nil {
				log.Printf("[job:%s] Failed to unmarshal report: %v", jobID, err)
				return
			}

			if report.Winner == nil {
				log.Printf("[job:%s] No winner to process PR for", jobID)
				return
			}

			// Retrieve latest job status
			job, err := db.GetJob(jobID)
			if err != nil {
				log.Printf("[job:%s] Failed to fetch job: %v", jobID, err)
				return
			}

			// Check auto-PR configuration
			if cfg.AutoPR && prCreator.CanCreatePR() {
				emit(jobID, "📤 **Auto PR** — Creating pull request...")

				owner, repo, number, err := gh.ParseIssueURL(job.IssueURL)
				if err != nil {
					log.Printf("[job:%s] Failed to parse issue URL: %v", jobID, err)
					emit(jobID, fmt.Sprintf("⚠️ Auto PR failed: invalid issue URL: %v", err))
					return
				}

				prReq := &gh.PRRequest{
					Owner:       owner,
					Repo:        repo,
					IssueNumber: number,
					Language:    job.Language,
					Title:       fmt.Sprintf("fix: resolve #%d via Raven AI", number),
					Body: fmt.Sprintf("## 🪶 Raven Auto-Fix for #%d\n\n"+
						"**Issue:** %s\n\n"+
						"**Winning Model:** `%s` (score: %.1f)\n\n"+
						"**RavenMind Consensus Report:**\n```\n%s\n```\n\n"+
						"---\n_This PR was automatically generated by [Raven](https://github.com/Shardz4/Raven)._",
						number, job.IssueTitle, job.WinnerModel, report.Winner.FinalScore, report.Summary),
					PatchCode: report.Winner.Patch.Code,
				}

				prResult, err := prCreator.CreatePR(prReq)
				if err != nil {
					emit(jobID, fmt.Sprintf("⚠️ Auto PR failed: %v", err))
				} else {
					job.PRURL = prResult.PRURL
					_ = db.UpdateJobResult(job)
					emit(jobID, fmt.Sprintf("✅ PR opened: %s", prResult.PRURL))
				}
			} else {
				log.Printf("[job:%s] Auto-PR disabled or GITHUB_TOKEN not configured", jobID)
			}
		}()
	})

	if err != nil {
		log.Fatalf("❌ Failed to subscribe to raven.consensus.winner: %v", err)
	}

	log.Println("✓ PR Agent ready and listening on subject", broker.SubjectConsensusWinner)

	// Keep alive
	sigCh := make(chan os.Signal, 1)
	signal.Notify(sigCh, syscall.SIGINT, syscall.SIGTERM)
	<-sigCh
}
